name: git_alert_publish
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v3

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5

      - name: Build and publish to pypi
        run: |
          uv build
          uv publish
